language: python
git:
  depth: false

credentials:
  - &pypi
    provider: pypi
    user: __token__
    password:
      secure: VX6k2AMOaYZxIhreapNb0HY9Cj+V+3BKbgS7mPg6rDCOtmwCLmvqH80UUZNd+xm/7HWfjv2yApxREYppf5QJLthWNhsd6p6ssdV64oM3DgO2hD14mbf0fd8O7fjCrMAPRQfrnrIsZL8LmH3kvr1yHmNId6z/7FNY68xcoxQe1Wz1KWaYn3lZNqQX0rrx9q/LQRd6R8J0F4F3/d1FQQLFdX+3Nb3CJb0Z/hn6tF2L+lmNZFvibJrB2QQ4ISG9Hgv1N8Vreqz3+xQepKaLaR1nNwAIh1rh3NxPf3UY9v6q/iTxeCKlilkvQ5CTJgG80xcnlcEm8jKzZ6a1HhTOMz1VDTCnaR4Za+7T31eAf5NVCKBqTtR6yX2hTigdn/3AQbN92E80/uGECNYAeDyCaXDPzdnad3vidrMZtRPrSrOUyV5cZNOGKx765JXv6LYJGaSfzEYWiXT8T9lIBca1sOjCrncA/ztD28sc5wvjEIHfipXY9UJ3eNRdh5z2t5aYXSXvIYgVHeSEEupuEDF1M8wwcH7PuSTXNOHUz9rPz/59+NLV5K4LRaWus7WmU4Ux4+H+hgHBUR8T2YNmwznta5qsnRT0SUFEZQPmY9VCU1h1NCYE8KF2ZWOItsmSbemwaFY6zRzKsdelD4JwG147zcTeV+xGumCbtv8wSlakPoNDc9M=
    on:
      branch: master
      tags: true

os:
  - linux
  - windows

python:
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8-dev'

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov

install:
  - pip install -r requirements.txt
  - pip install ".[tests]" .

after_success:
  - codecov # submit coverage

script:
  pytest

deploy:
  provider: pypi
  user: __token__
  password:
    secure: VX6k2AMOaYZxIhreapNb0HY9Cj+V+3BKbgS7mPg6rDCOtmwCLmvqH80UUZNd+xm/7HWfjv2yApxREYppf5QJLthWNhsd6p6ssdV64oM3DgO2hD14mbf0fd8O7fjCrMAPRQfrnrIsZL8LmH3kvr1yHmNId6z/7FNY68xcoxQe1Wz1KWaYn3lZNqQX0rrx9q/LQRd6R8J0F4F3/d1FQQLFdX+3Nb3CJb0Z/hn6tF2L+lmNZFvibJrB2QQ4ISG9Hgv1N8Vreqz3+xQepKaLaR1nNwAIh1rh3NxPf3UY9v6q/iTxeCKlilkvQ5CTJgG80xcnlcEm8jKzZ6a1HhTOMz1VDTCnaR4Za+7T31eAf5NVCKBqTtR6yX2hTigdn/3AQbN92E80/uGECNYAeDyCaXDPzdnad3vidrMZtRPrSrOUyV5cZNOGKx765JXv6LYJGaSfzEYWiXT8T9lIBca1sOjCrncA/ztD28sc5wvjEIHfipXY9UJ3eNRdh5z2t5aYXSXvIYgVHeSEEupuEDF1M8wwcH7PuSTXNOHUz9rPz/59+NLV5K4LRaWus7WmU4Ux4+H+hgHBUR8T2YNmwznta5qsnRT0SUFEZQPmY9VCU1h1NCYE8KF2ZWOItsmSbemwaFY6zRzKsdelD4JwG147zcTeV+xGumCbtv8wSlakPoNDc9M=
  on:
    branch: master
    tags: true
